tag = "octoguns-start"
writes = [
    "octoguns-Position",
    "octoguns-Character",
    "octoguns-Health",
    "octoguns-Map",
    "octoguns-MapObjects",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-Global",
    "octoguns-Player"

]
